full_text=〉
align=center
color=#ffffff
separator=false
separator_block_width=7

[time]
instance=vn
TZ=Asia/Ho_Chi_Minh
command=date +%T
interval=1

[separator]

[battery]
command=~/.config/sway/i3blocks/battery.sh
interval=10
