require("presence").setup({
  auto_update = true,
  neovim_image_text = "Neovim - Hyperextensible Vim-based Text Editor",
  main_image = "neovim",
  client_id = "793271441293967371",
  log_level = nil,
  debounce_timeout = 10,
  enable_line_number = true,
  blacklist = {},
  buttons = {
    { label = "View Repository", url = "https://github.com/huydna" },
  },
  show_time = true,

  -- Cooler status texts with more personality
  editing_text = "✏️ Hacking on %s",
  file_explorer_text = "📂 Exploring %s",
  git_commit_text = "🔀 Committing changes",
  plugin_manager_text = "🔌 Managing plugins",
  reading_text = "📖 Reading %s",
  workspace_text = "💻 Working on %s",
  line_number_text = "Line %s/%s",

  -- Custom file assets for common languages (icon, tooltip)
  file_assets = {
    lua = { "lua", "Lua" },
    nix = { "nix", "Nix" },
    rs = { "rust", "Rust" },
    go = { "go", "Go" },
    py = { "python", "Python" },
    js = { "javascript", "JavaScript" },
    ts = { "typescript", "TypeScript" },
    tsx = { "react", "React (TSX)" },
    jsx = { "react", "React (JSX)" },
    vue = { "vue", "Vue.js" },
    html = { "html", "HTML" },
    css = { "css", "CSS" },
    json = { "json", "JSON" },
    yaml = { "yaml", "YAML" },
    toml = { "toml", "TOML" },
    md = { "markdown", "Markdown" },
    sh = { "shell", "Shell Script" },
    dockerfile = { "docker", "Dockerfile" },
    sql = { "database", "SQL" },
    tex = { "latex", "LaTeX" },
    typ = { "typst", "Typst" },
  },
})
