[window]

opacity = 0.95

padding.x = 5
padding.y = 5

decorations = "Full"
decorations_theme_variant = "Dark"

[font]

normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"

size = 13.0
