require("plugins.configs.ui")
require("plugins.configs.editor")
require("plugins.configs.git")
require("plugins.configs.completion")
require("plugins.configs.lsp")
require("plugins.configs.formatting")
require("plugins.configs.misc")
