require("plugins.configs.theme")
require("plugins.configs.filetree")
require("plugins.configs.telescope")
require("plugins.configs.language_services")
require("plugins.configs.presence")
require("plugins.configs.git")
